[package]
name = "opengl-book-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.60.0"
image = "0.25.6"
# only needed from chapter 3 on
tobj = "4.0.3"
num = "0.4.3"
rand = "0.9.2"
